- name: run tests against {{ environment_name }}
  hosts: tag_environment_{{ environment_name }}
  become: true
  tasks:
    - name: run phantomjs against {{ item }}
      local_action: command phantomjs ./tests/acceptance.js {{ item }}
      with_items: play_hosts
