- name: run tests against {{ environment }}
  hosts: tag_environment_{{ environment }}
  become: true
  tasks:
    - name:
      command: phantomjs ./tests/acceptance.js {{ item }}
      with_items: play_hosts
